language: php

php:
  - 5.6
  - 7.0

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - phpcs --ignore=/vendor/*,/tests/Resources/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: "nicolasbastien.pro@gmail.com"
